### ISSUE TITLE
Downloading chapter/volume ranges from MangaDex causing pages to download partially rendered

### ISSUE THREAD

**Issue by Panthon13** [elboletaire/manga-downloader#16]
Downloading a range of manga from MangaDex (specifically Made in Abyss) causes the downloader to seemingly grab the images before they are finished loading, resulting in partially rendered pages. Downloading each chapter 1 by 1 is fine, but that may take a while to grab a whole series that's the size of something like Berserk or Naruto. The issue is inconsistent, sometimes the download messes up, sometimes it's fine. The pages that are affected seem to vary when retrying the download, too. Larger ranges seem to mess up more pages.

Execution example: 
manga-downloader.exe https://mangadex.org/title/80422e14-b9ad-4fda-970f-de370d5fa4e5/made-in-abyss --language en 3-5

Book 4, page 2:
![image](https://user-images.githubusercontent.com/30754918/213708018-d550ed66-b41e-4875-936b-8798f7c0e6fa.png)

Book 5, page 14:
![image](https://user-images.githubusercontent.com/30754918/213708201-f82b2b3f-cfca-4085-8c89-a253164c23af.png)

**Comment by elboletaire** [comment]
hhhmm... weird. I'll have to take a look, it may be related to when I added the `--bundle` arg. Could you try with version 0.0.6 (the prior to adding `--bundle`) and tell me if you have issues there? Personally I've been downloading full series from mangadex and didn't have this issue, but I think I did it before adding the bundle feature.

If not, I'll try to try it by myself and also to release a fix as soon as I can 😃

**Comment by Panthon13** [comment]
Could it be related to the resolution of images? They're initially around 2200x3000 each. I haven't had problems with other series where they are around 1200 or less. I'll give the older version a shot.

**Comment by elboletaire** [comment]
It could, actually.. haven't tried before with such image size. But from what I know, it should be fine, since I'm (theoretically) waiting for the downloads to complete. 

Can't say much without trying it and debugging it myself (which will hopefully be in a few hours).

I'll keep you informed

**Comment by elboletaire** [comment]
Oops, I didn't want to close the issue right away before you try first, but I think I properly fixed it. There were some issues when downloading the files + I changed something.

After these changes I've tried downloading 10 numbers of the Made in Abyss series and all the chapters are properly downloaded. 

I think due to these changes some http errors that weren't properly captured are now captured, and you may see some issues downloading pages for certain chapters:

![imatge](https://user-images.githubusercontent.com/153305/213757676-e9162d7e-b0a7-49a2-bf1a-4d81f36957c2.png)

In case these happens, just redownload the failing chapters and it should be good to read (I have a pending issue to add some kind of retry for these cases).

I was not seeing these errors before, so I guess that was the problem: the connection was being closed due to http errors and it was not properly catched by my code. 

Since I have some other changes pending to be published, I'll create a new release right away so you can try these changes.

**Comment by elboletaire** [comment]
[v0.0.9](https://github.com/elboletaire/manga-downloader/releases/tag/v0.0.9) should be available for download in a few moments

**Comment by Panthon13** [comment]
I've tested v0.0.9, I'm now getting error printouts correctly.
